<footer>
    <p>CSC 174: Advanced Front-end Web Design and Development </p>
</footer>
<nav>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="mingyuan.php">Mingyuan</a></li>
        <li><a href="nan.php">Nan Xie</a></li>
        <li><a href="shawn.php">Shawn Chen</a></li>
    </ul>
</nav>
<script src="https://code.jquery.com/jquery.js"></script>
<script src="js/menu-highlighter.js"></script>